export const Consts = {
  AttributeKeyRegexp: /^[a-zA-Z0-9_]{1,30}$/,
  AttributeStringMaxLengthMEP: 64,
  AttributeStringMaxLengthCEP: 300,
  AttributeURLMaxLength: 2048,
  EventDataLabelMaxLength: 200,
  EventDataStringMaxLength: 300,
  EventDataTagMaxLength: 64,
  EventNameRegex: /^[a-zA-Z0-9_]{1,30}$/,
  MaxEventAttributesCount: 20,
  MaxEventArrayAttributesCount: 10,
  MaxEventArrayItems: 25,
  MaxEventObjectDepth: 3,
  MaxProfileAttributesCount: 50,
  MaxProfileArrayItems: 25,
  MaxProfileArrayAttributesCount: 15,
  EmailAddressMaxLength: 128,
  EmailAddressRegexp: /^[^@]+@[A-z0-9\-.]+\.[A-z0-9]+$/,
};
